### ISSUE TITLE
Add more dependencies in PKGBUILD 

### ISSUE THREAD

**Issue by JustSimplyKyle** [gissf1/zram-hibernate#2]
There are no current listed dependencies.
But looking at the code, at least `awk` `bash` `sed` and `grep` is in it.

**Comment by JustSimplyKyle** [comment]
You can also add detection when a command doesn't exist(aka not installed) in the script itself, I've seen this practice in several other scripts too!

**Comment by gissf1** [comment]
At least for Arch Linux, all the packages it uses are part of the base install.

Was there something that it tried to use that wasn't installed by default on your install?

I updated the PKGBUILD with the ones I noticed when I skimmed through the file, just to be complete.

**Comment by JustSimplyKyle** [comment]
Yeah, it's all defaultly installed(`base-devel`) except bash, but it's still considered good practice to include all the dependencies.
